import React from 'react';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    height: '100%',
    width: '100%',
    backgroundColor:
      'linear-gradient(180deg, #534040 0%, rgba(164, 18, 18, 0.84) 100%)',
    opacity: 0.9,
  },
  tictactitle: {
    fontFamily: 'monospace',
    fontSize: 45,
    textAlign: 'center',
    color: '#FFE1E1',
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowRadius: 4,
    textShadowOffset: {width: 0, height: 4},
    paddingTop: 50,
  },
  foestitle: {
    fontFamily: 'monospace',
    fontSize: 60,
    textAlign: 'center',
    color: '#FFE1E1',
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowRadius: 4,
    textShadowOffset: {width: 0, height: 4},
    paddingBottom: 45,
  },
  homeImg: {
    height: 225,
    width: 225,
    marginBottom: 30,
  },
  backgrounImg: {
    height: '100%',
    width: '100%',
    resizeMode: 'cover',
    alignItems: 'center',
  },
  homeButton: {
    backgroundColor: '#FFFFFF',
    height: 60,
    width: 275,
    margin: 10,
    alignItems: 'center',
    borderColor: '#000000',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    shadowColor: 'rgba(0,0,0,0.25)',
    shadowOffset: {width: 0, height: 4},
    shadowRadius: 4,
    justifyContent: 'center',
  },
  homtButtonText: {
    fontSize: 25,
    fontFamily: 'monospace',
  },
  waitingImg: {
    marginTop: 10,
    height: 300,
    width: 300,
  },
  waitingText: {
    color: '#FFFFFF',
    fontFamily: 'monospace',
    fontSize: 24,
    alignSelf: 'flex-start',
    marginLeft: 20,
    marginBottom: 25,
  },
  startButton: {
    backgroundColor: '#FFFFFF',
    height: 60,
    width: 120,
    margin: 10,
    alignItems: 'center',
    borderColor: '#000000',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    shadowColor: 'rgba(0,0,0,0.25)',
    shadowOffset: {width: 0, height: 4},
    shadowRadius: 4,
    justifyContent: 'center',
  },
  startText: {
    fontFamily: 'monospace',
    fontSize: 20,
  },
  buttonRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginTop: 75,
    marginLeft: 80,
    //justifyContent: 'flex-start',
  },
  group: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  groupItem: {
    height: 100,
    width: 100,
    backgroundColor: 'white',
    borderStyle: 'solid',
    borderColor: 'black',
    borderWidth: 2,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    paddingTop: 12,
  },
  itemText: {
    fontWeight: 'bold',
    fontSize: 50,
  },
  gameButtonRow: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  gameTitle: {
    color: '#FFFFFF',
    fontFamily: 'monospace',
    fontSize: 24,
    alignSelf: 'center',
    marginLeft: 20,
    marginBottom: 15,
    marginTop: 40,
  },
  dropdown: {
    backgroundColor: '#FFFFFF',
    height: 60,
    width: 275,
    margin: 10,
    borderColor: '#000000',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    shadowColor: 'rgba(0,0,0,0.25)',
    shadowOffset: {width: 0, height: 4},
    shadowRadius: 4,
    justifyContent: 'center',
  },
});

export default styles;
